[package]
name = "game_2"
version = "0.0.2"
authors = ["thea"]
edition = "2018"

[dependencies]
rand = "0.8.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
json = { version = "0.12.4"}